apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flask-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Seshadri724/gitops-microservice-monitoring.git
  ref:
    branch: main